### ISSUE TITLE
Raspberry Pi Imager v1.2 not working, use balenaEtcher instead

### ISSUE THREAD

**Issue by jaimeHMol** [nmcclain/raspberian-firstboot#1]
I am using this image and it is working great. Awesome job!

Just want to add that I couldn't flash the image using the official Raspberry program (Raspberry Pi Imager v1.2), however using balenaEtcher flasher (v1.5.86) all worked ok. In case someone has experienced the following error:

![Captura de pantalla 2020-05-11 a la(s) 9 57 09 p  m](https://user-images.githubusercontent.com/28209920/81628526-47cb9f00-93d7-11ea-8f7b-3761011823f0.png)

**Comment by nmcclain** [comment]
Added a recommendation to the README - thank you for the feedback!
