### ISSUE TITLE
Continuity in the "do it yourself" section

### ISSUE THREAD

**Issue by tgelite** [nmcclain/raspberian-firstboot#11]
While building an instance of the `2021-03-04-raspios-buster-armhf-lite-firstboot.img` I am noticing a gap in the reader's steps covered in the ["How to reproduce this image yourself"](https://github.com/nmcclain/raspberian-firstboot#how-to-reproduce-this-image-yourself) section of the readme.md

For first time users playing along from home trying to build their first image, you want to include unmounting the second partition, mounting the first, and then dropping their custom firstboot.sh into the /boot directory.

Something like

```
...
7. Unmount the second partition of the source image.
8. Mount the first partition of the source image (using examples above) which is the "boot" volume
9. Copy your custom firstboot.sh script into the first partition and make it executable
# cp /path/to/your/fistboot.sh /mnt/; chmod +x /mnt/firstboot.sh
10. Unmount the first partition of the source image ( umount /mnt/
11. Carefully test & validate the image before distributing!
```

**Comment by nmcclain** [comment]
My intent with the "do it yourself" section was to just show how to reproduce the image that is released to the public, but I definitely understand the confusion.

I added a note to the top of this section to hopefully clarify. I'm very open to suggestions/edits if you don't think this clears things up! Thank you!!
