### ISSUE TITLE
"Could not get lock /var/lib/dpkg/lock-frontend" when installing apt packages

### ISSUE THREAD

**Issue by janoskut** [nmcclain/raspberian-firstboot#13]
Sometimes when running the firstboot scripts and installing `apt` packages, I'm getting this error:
```
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
This is possibly because of `apt-daily.service` and `apt-daily-upgrade.service` also running on system start, [as pointed out in this answer](https://unix.stackexchange.com/a/480986/106804).

I think it would be a good idea to add `apt-daily.service apt-daily-upgrade.service` to [`After=`](https://github.com/nmcclain/raspberian-firstboot/blob/master/firstboot.service#L3) in the service unit.

**Comment by nmcclain** [comment]
Added to main. THANK YOU!!
