### ISSUE TITLE
Release 8 appears to be missing the /etc/systemd/system/multi-user.target.wants/firstboot.service link

### ISSUE THREAD

**Issue by jmank** [nmcclain/raspberian-firstboot#15]
I attempted to use your latest release, 2021-05-07-raspios-buster-armhf-lite-firstboot.zip,
and it did not work for me.   I'm pretty sure it does not work because  the required link in multi-user.target.wants is missing from the image.    Once I added the link to enable the service (by mounting the root filesystem on the flash card and creating the link),  it worked correctly for me.

cd /etc/systemd/system/multi-user.target.wants && ln -s /lib/systemd/system/firstboot.service .

**Comment by nmcclain** [comment]
I've verified this definitely exists in the latest release:
https://github.com/nmcclain/raspberian-firstboot/releases/tag/2021-10-30-raspios-bullseye-armhf-lite-firstboot

```
$ ls /etc/systemd/system/multi-user.target.wants | grep first
firstboot.service
```

Sorry for the trouble!
