### ISSUE TITLE
Could we update to the latest version of Raspberry OS?

### ISSUE THREAD

**Issue by kinchahoy** [nmcclain/raspberian-firstboot#2]
This it the only easy to use automation script I've found, and it's part of my fairly extensive turnkey ansible based setup process. I'm not looking forward to setting up a VM to make these updates to the latest Raspberry OS. Would you consider updating your repo with the latest version?

**Comment by nmcclain** [comment]
I will do this next week.

**Comment by nmcclain** [comment]
Finally updated, sorry for the delay: https://github.com/nmcclain/raspberian-firstboot/releases/tag/2020-08-20-raspios-lite-firstboot

Tested on RPiv4B and v2B1.1.

Please let me know if you run into issues!
