### ISSUE TITLE
strange date "race condition" on firstboot with current 8-20-2020 image?

### ISSUE THREAD

**Issue by tgelite** [nmcclain/raspberian-firstboot#4]
Great tool and writeup! Thanks for sharing this.   I have a strange issue when I set up the firstboot.sh to do the following:

`#!/bin/bash` 
`# Minimalist test of getting the pi setup automatically on first boot`
`/usr/bin/touch /boot/ssh`
`/usr/bin/apt update`
`/usr/bin/apt install -y --fix-missing git`

The firstboot.service fails with the following output in the systemctl output:

`pi@raspberrypi:~ $ systemctl status firstboot.service`
`● firstboot.service - FirstBoot`
`   Loaded: loaded (/lib/systemd/system/firstboot.service; enabled; vendor preset: enabled)`
`   Active: failed (Result: exit-code) since Mon 2020-09-28 21:37:57 BST; 2min 28s ago`
` Main PID: 625 (code=exited, status=1/FAILURE)`
`Sep 28 21:37:57 raspberrypi firstboot.sh[625]: E: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 39d 6h 5min 33s). Updates for this repository will not be applied.`
`Sep 28 21:37:57 raspberrypi firstboot.sh[625]: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`
`Sep 28 21:37:57 raspberrypi firstboot.sh[625]: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)`
`Sep 28 21:37:57 raspberrypi firstboot.sh[625]: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?`
`Sep 28 21:37:57 raspberrypi systemd[1]: firstboot.service: Main process exited, code=exited, status=1/FAILURE`
`Sep 28 21:37:57 raspberrypi systemd[1]: firstboot.service: Failed with result 'exit-code'.`
`Sep 28 21:37:57 raspberrypi systemd[1]: Failed to start FirstBoot.`

When I log into the shell after this fails, and do a date command I get what is the current date/time.  I dont understand how this could be failing unless there is some kind of situation where the actual system date/time on first boot does not get updated until the pi fully boots?

Here is the date command after failure and enabling ssh to connect and start copy/pasting the failure messages...
`pi@raspberrypi:~ $ date`
`Mon 28 Sep 21:42:48 BST 2020`

Do I need to be doing something with system date within my script to avoid this?

Thanks in advance

**Comment by nmcclain** [comment]
Hi @tgelite - I think the important error message is:
`Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?`

There must be some other instance of apt/dpkg running at the same time as your script. I highly suspect it is the `apt-daily.service` or `apt-daily-upgrade.timer` service, which likely gets started on boot.

I will look into a solution to work around this issue.

**Comment by tgelite** [comment]
FYI this fixed the issue by modifying my apt command:

`/usr/bin/apt update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update`

Per discussion here:

https://askubuntu.com/questions/1096930/sudo-apt-update-error-release-file-is-not-yet-valid

I think that the lock is left open as the failure took place due to the message "Sep 28 21:37:57 raspberrypi firstboot.sh[625]: E: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 39d 6h 5min 33s). Updates for this repository will not be applied."  I'll re-image a card and test this as well

**Comment by tgelite** [comment]
Ok this time it worked with the modified update command I gave:

```
pi@raspberrypi:~ $ systemctl status firstboot.service
● firstboot.service - FirstBoot
   Loaded: loaded (/lib/systemd/system/firstboot.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-09-28 22:48:21 BST; 2min 57s ago
 Main PID: 617 (code=exited, status=0/SUCCESS)

Sep 28 22:48:14 raspberrypi firstboot.sh[617]: Unpacking git (1:2.20.1-2+deb10u3) ...
Sep 28 22:48:16 raspberrypi firstboot.sh[617]: Setting up libcurl3-gnutls:armhf (7.64.0-4+deb10u1) ...
Sep 28 22:48:16 raspberrypi firstboot.sh[617]: Setting up liberror-perl (0.17027-2) ...
Sep 28 22:48:16 raspberrypi firstboot.sh[617]: Setting up git-man (1:2.20.1-2+deb10u3) ...
Sep 28 22:48:16 raspberrypi firstboot.sh[617]: Setting up git (1:2.20.1-2+deb10u3) ...
Sep 28 22:48:16 raspberrypi firstboot.sh[617]: Processing triggers for man-db (2.8.5-2) ...
Sep 28 22:48:19 raspberrypi firstboot.sh[617]: Processing triggers for libc-bin (2.28-10+rpi1) ...
Sep 28 22:48:21 raspberrypi systemd[1]: firstboot.service: Succeeded.
Sep 28 22:48:21 raspberrypi systemd[1]: Started FirstBoot.
```

This looks like its fixed, probably something to do with updates to the repo vs age of image? ¯\_(ツ)_/¯

**Comment by nmcclain** [comment]
Captured your improved `apt update` command in the example, thank you!!
