### ISSUE TITLE
Unclear README.md Instructions

### ISSUE THREAD

**Issue by Picajoluna** [nmcclain/raspberian-firstboot#6]
Hi there,

I got confused by the order of instructions provided in the Readme. The 'Quick Start' section  states to load the firstboot.sh / wpa_supplicant.conf / files onto the SD card, unmount it, and only afterwards to flash it with balena etcher before inserting into the Pi...  This did not work for me until I reversed the order, first flashing, then loading everything (including firstboot.sh). I guess it makes sense – every time I formatted the card with balena etcher, it would squash any files I'd stored before...
Maybe my understanding of the order is still incorrect, but the firstboot script now works for me (thanks for this by the way – lifesaver for myself, a college student, trying to entirely 'headlessly' connect to a WPA2 Enterprise network).

**Comment by nmcclain** [comment]
I completely understand what you're saying. I think there are two ways to use the image:
1. Download the image, customize it with firstboot scripts, then flash the customized image to your SD card.
2. Download the image, flash the image to your SD card, then customize it with firstboot scripts.

The Quick Start documents the first approach.

I'll update the docs to describe both approaches and try to make this a little more clear.

Also note that this (or something like it) will soon be added to the base raspios distro: https://github.com/RPi-Distro/raspberrypi-sys-mods/pull/40

**Comment by nmcclain** [comment]
I clarified this in the README.

Thanks for the suggestion! Very open to edits/improvements.

**Comment by Picajoluna** [comment]
This is perfect! Thanks.
