### ISSUE TITLE
With not use guestmount -v --pid-file "$PIDFILE" -a "$IMG" -m /dev/sda2 -m /dev/sda1:/boot "$MNT"

### ISSUE THREAD

**Issue by bastien-roucaries** [nmcclain/raspberian-firstboot#8]
Hi,

You could use guestmount to mount magically the rasb image.

Thanks

bastien

**Comment by nmcclain** [comment]
Thank you for the suggestion - added to README.md.

I feel like this is a lot more heavyweight than `mount_offset_tool`, but it's really good to have options!
